server:
  port: 8082
spring:
  application:
    name: auth-service
  cloud:
    config:
      uri: http://localhost:8888
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}
      redirect-uri: http://localhost:8082/api/auth/google-redirect
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
kafka:
  topic:
    user-creation: user-creation-topic
    user-login: user-login-topic
    user-update: user-update-topic
    user-deletion: user-deletion-topic

keycloak:
  realm: social-network
  ssl-required: external
  resource: auth-service
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET}
  use-resource-role-mappings: true
  admin:
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}
    clientId: admin-cli
  cors: true
  principal-attribute: preferred_username
  auth-server-url: http://localhost:8080
  providers:
    google:
      clientId: ${GOOGLE_CLIENT_ID}
      clientSecret: ${GOOGLE_CLIENT_SECRET}
      defaultScope: openid email profile

logging:
  level:
    org.keycloak: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    preferIpAddress: true