server:
  port: 8081
spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/social-network
  main:
    web-application-type: reactive
  cloud:
    config:
      uri: http://localhost:8888
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:3000
              # Add other origins as needed
            allowedMethods: [ GET, POST, PUT, DELETE, OPTIONS ]
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /$\{segment}

        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /$\{segment}

        - id: chat-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/chat/**
          filters:
            - RewritePath=/api/chat/(?<segment>.*), /$\{segment}

        - id: notification-service
          uri: http://localhost:8085
          predicates:
              - Path=/api/notifications/**
          filters:
              - RewritePath=/api/notifications/(?<segment>.*), /$\{segment}

        - id: friend-service
          uri: http://localhost:8086
          predicates:
              - Path=/api/friends/**
          filters:
              - RewritePath=/api/friends/(?<segment>.*), /$\{segment}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/