server:
  port: 8081
spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:3000
              - http://localhost:4200
              # Add other origins as needed
            allowedMethods: [ GET, POST, PUT, DELETE, OPTIONS ]
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: auth-service
#          uri: lb://auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /$\{segment}

        - id: user-service
#          uri: lb://user-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /$\{segment}

        - id: chat-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/chat/**
          filters:
            - RewritePath=/api/chat/(?<segment>.*), /$\{segment}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/