server:
  port: 8081
spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/social-network
  main:
    web-application-type: reactive
    allow-circular-references: true
  cloud:
    config:
      uri: http://localhost:8888
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:3000
              # Add other origins as needed
            allowedMethods: [ GET, POST, PUT, DELETE, OPTIONS ]
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
            exposed-headers:
              -"Sec-WebSocket-Accept"
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /$\{segment}

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /$\{segment}

        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/api/chat/**
          filters:
            - RewritePath=/api/chat/(?<segment>.*), /$\{segment}
        - id: chat-service-websocket
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/ws/**
          filters:
            - RemoveRequestHeader=Origin

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
              - Path=/api/notifications/**
          filters:
              - RewritePath=/api/notifications/(?<segment>.*), /$\{segment}

        - id: friend-service
          uri: lb://FRIEND-SERVICE
          predicates:
              - Path=/api/friends/**
          filters:
              - RewritePath=/api/friends/(?<segment>.*), /$\{segment}

        - id: ai-chatbot-service
          uri: lb://AI-CHATBOT-SERVICE
          predicates:
            - Path=/api/ai-chatbot/**
          filters:
            - RewritePath=/api/ai-chatbot/(?<segment>.*), /$\{segment}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    preferIpAddress: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG