server:
  port: 8084
spring:
  application:
    name: chat-service
  cloud:
    config:
      uri: http://localhost:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}
          jwk-set-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs
  data:
    mongodb:
      uri: mongodb://localhost:27017/chat_db

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: chat-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
keycloak:
  realm: social-network
  ssl-required: external
  resource: auth-service
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET}
  use-resource-role-mappings: true
  admin:
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}
    clientId: admin-cli
  cors: true
  principal-attribute: preferred_username
  auth-server-url: http://localhost:8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
